# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_data_quality'
version: '1.0.0'
profile: 'dbt_data_quality'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Конфигурация моделей по слоям (рекомендуется)
# =============================================
models:
  dbt_data_quality:
    # Staging — всегда view (лёгкие, не храним)
    staging:
      +materialized: view
      +tags: ["bronze", "staging"]

    # Intermediate — table + incremental где возможно
    intermediate:
      +materialized: table
      +tags: ["intermediate"]
      +incremental_strategy: append   # или merge, в зависимости от prepare

    # Marts / Data Quality — table (результаты ошибок)
    marts:
      +materialized: table
      +tags: ["marts", "data_quality"]
      data_quality:
        +schema: data_quality   # схема в БД

    # Пример для конкретного подпроекта
    marts__data_quality__07_02:
      +materialized: table
